### ISSUE TITLE
Breaking change in 0.2.1 from 0.2.0

### ISSUE THREAD

**Issue by eritislami** [zackradisic/node-soundcloud-downloader#38]
After updating to 0.2.1 I am getting this error
`(node:9432) UnhandledPromiseRejectionWarning: TypeError: scdl.isValidUrl is not a function`

Usage:
```js
const scdl = require("soundcloud-downloader");
scdl.isValidUrl(url)
```

**Comment by haruzinh0** [comment]
ive found an fix for this. change all scdl to scdl.default.isValidUrl, scdl.default.getInfo, etc. hope i helped you.

cheers

**Comment by haruzinh0** [comment]
idk why owner changed to this in the docs and in package but, thats it.

**Comment by zackradisic** [comment]
With the new update I introduced a new function to create new instances of SCDL and that changed the exports. You must do this now:

```javascript
const scdl = require("soundcloud-downloader").default
```

**Comment by eritislami** [comment]
Thanks will try this.
